export interface SlashCommand {
  name: string;
  description: string;
  local?: boolean;
}

// This is deliberately a small data catalog: commands can be discoverable before
// every integration has a local implementation.
const slashCommandRows = [
  ["clear", "Clear the visible conversation and model history", true],
  ["compact", "Trim old history to reduce token usage", true],
  ["help", "List Garuda slash commands", true],
  ["status", "Show the active provider, model, and context estimate", true],
  ["context", "Show the current context estimate", true],
  ["skills", "List bundled coding skills", true],
  ["tools", "List tools available to the agent", true],
  ["debug", "Trace a failure and verify the fix"],
  ["security", "Inspect code for security risks"],
  ["performance", "Find hot paths and unnecessary work"],
  ["refactor", "Improve structure while preserving behavior"],
  ["test", "Design focused tests for the current task"],
  ["document", "Write concise project documentation"],
  ["exit", "Exit Garuda", true],
  ["quit", "Exit Garuda", true],
  ["model", "Show or request a model change"],
  ["provider", "Show or request a provider change"],
  ["sessions", "List saved conversations"],
  ["files", "List files currently in context"],
  ["ctx", "Show context window usage"],
  ["repomap", "Show the repository map"],
  ["resume", "Resume a saved conversation"],
  ["rename", "Rename the current conversation"],
  ["branch", "Create a conversation branch"],
  ["rewind", "Restore a previous conversation state"],
  ["export", "Export the current conversation"],
  ["copy", "Copy the latest response"],
  ["continue", "Continue the current task"],
  ["replay", "Replay a saved session"],
  ["tag", "Tag the current session"],
  ["goal", "Set or inspect a session goal"],
  ["tasks", "List background tasks"],
  ["session", "Show session metadata"],
  ["desktop", "Open the session in a desktop client"],
  ["mobile", "Show mobile session access"],
  ["add-dir", "Add a working directory"],
  ["init", "Create project instructions"],
  ["memory", "Manage persistent memory"],
  ["dream", "Consolidate durable memories"],
  ["knowledge", "Manage the project knowledge graph"],
  ["wiki", "Manage the project wiki"],
  ["cost", "Show estimated session cost"],
  ["request-size", "Show context contributors"],
  ["cache-stats", "Show prompt cache statistics"],
  ["login", "Sign in to a supported account"],
  ["logout", "Sign out of a supported account"],
  ["onboard-github", "Connect GitHub Copilot"],
  ["usage", "Show provider usage"],
  ["extra-usage", "Configure extra usage"],
  ["effort", "Set model effort level"],
  ["set-context-window", "Set a model context-window override"],
  ["clear-context-window", "Clear a model context-window override"],
  ["smartroute", "Configure simple/strong model routing"],
  ["diff", "View uncommitted changes"],
  ["review", "Review a pull request"],
  ["security-review", "Review pending changes for security issues"],
  ["pr-comments", "Fetch pull request comments"],
  ["auto-fix", "Configure automatic validation after edits"],
  ["plan", "Create or inspect an implementation plan"],
  ["install-github-app", "Connect GitHub Actions"],
  ["install-slack-app", "Connect Slack"],
  ["mcp", "Manage MCP servers"],
  ["connect", "Connect an external provider"],
  ["models", "List available models"],
  ["lsp", "Inspect language-server integrations"],
  ["ide", "Manage IDE integrations"],
  ["plugin", "Manage plugins"],
  ["reload-plugins", "Reload plugins"],
  ["agents", "Manage agent configurations"],
  ["hooks", "View hook configurations"],
  ["permissions", "Manage tool permissions"],
  ["chrome", "Manage browser integration"],
  ["config", "Open configuration"],
  ["theme", "Change the terminal theme"],
  ["logo", "Change the startup logo"],
  ["color", "Change the prompt color"],
  ["keybindings", "Configure keybindings"],
  ["vim", "Toggle Vim editing mode"],
  ["statusline", "Configure the status line"],
  ["terminal-setup", "Install terminal keybindings"],
  ["commit-message", "Configure commit attribution"],
  ["buddy", "Manage the optional companion"],
  ["ads", "Manage sponsored tips"],
  ["stickers", "Open the sticker store"],
  ["doctor", "Diagnose Garuda configuration"],
  ["diagnostics", "Show captured diagnostics"],
  ["stats", "Show usage statistics"],
  ["insights", "Analyze session activity"],
  ["release-notes", "Show release notes"],
  ["feedback", "Send feedback"],
  ["cache-probe", "Probe provider prompt caching"],
  ["update", "Check for Garuda updates"],
  ["privacy-settings", "Show privacy settings"],
] as const;

export const SLASH_COMMANDS: SlashCommand[] = slashCommandRows.map(([name, description, local]) => ({
  name,
  description,
  local,
}));

export function getSlashCommand(name: string): SlashCommand | undefined {
  return SLASH_COMMANDS.find((command) => command.name === name);
}